POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBoZW5vbWVuYWwiLCJpZCI6IjYzNjJlNGM0NTkzZWViOWU4OWMyMmZjYiIsImlhdCI6MTY2NzUxMjM3NSwiZXhwIjoxNjY3NTE1OTc1fQ.jBS5gIKOH0ENYSGZuR_vN7Dpqpx6QVomQnB4dw4yiMk

{
    "title": "Another Blog",
    "author": "Bora Balmumcu",
    "url": "http://example.org",
    "likes": 1
}